# Generated by Django 5.0.2 on 2026-03-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("father_name", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("course_department", models.CharField(max_length=150)),
                ("enrollment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["registration_number"], name="students_reg_number_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["status"], name="students_status_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["enrollment_date"], name="students_enrollment_date_idx"),
        ),
    ]
