# Generated by Django 5.0.2 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_seed_students_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="students/profile_pictures/"),
        ),
    ]
