# Generated by Django 5.0.2 on 2026-03-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0005_add_employee_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("subject_name", models.CharField(max_length=150)),
                ("subject_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("total_marks", models.PositiveIntegerField()),
                ("pass_marks", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["subject_code"], name="subjects_code_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["status"], name="subjects_status_idx"),
        ),
    ]
