# Generated by Django 5.0.2 on 2026-03-15

from django.db import migrations


def seed_subjects_permissions(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    actions = ["view", "add", "change", "delete", "all"]
    permissions = {}

    for action in actions:
        permission, _ = Permission.objects.get_or_create(
            module="subjects",
            action=action,
            defaults={"description": f"Subjects {action}"},
        )
        permissions[action] = permission

    role_permissions = {
        "admin": ["all"],
        "receptionist": ["view", "add", "change"],
        "viewer": ["view"],
    }

    for role_name, role_actions in role_permissions.items():
        for action in role_actions:
            RolePermission.objects.get_or_create(
                role_name=role_name,
                permission=permissions[action],
            )


def reverse_seed_subjects_permissions(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    subjects_permissions = Permission.objects.filter(module="subjects")
    RolePermission.objects.filter(permission__in=subjects_permissions).delete()
    subjects_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
        ("core", "0008_add_subjects_module_choice"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_subjects_permissions, reverse_seed_subjects_permissions),
    ]
