# Generated by Django 6.0.2 on 2026-02-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_seed_schedule_permissions"),
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleslot",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_slots",
                to="trainers.trainer",
            ),
        ),
    ]
