# Generated by Django 6.0.2 on 2026-02-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_scheduleslot_trainer"),
        ("staff", "0006_remove_staff_staff_att_st_idx_alter_staff_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleslot",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_slots",
                to="staff.trainer",
            ),
        ),
    ]
