# Generated by Django 6.0.2 on 2026-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_inventory_permissions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='inventory_e_locatio_9f8a5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='inventory_e_reorder_f35c58_idx',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
    ]
