# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_seed_members_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="id_card_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="members/profile_pictures/"),
        ),
    ]
