# Generated by Django 5.0.2 on 2026-04-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0005_add_employee_gender"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "Option A"), ("B", "Option B"), ("C", "Option C"), ("D", "Option D")],
                        max_length=1,
                    ),
                ),
                ("marks", models.PositiveIntegerField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions_created",
                        to="employees.employee",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["subject"], name="questions_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["difficulty_level"], name="questions_difficulty_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["created_by"], name="questions_created_by_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["created_at"], name="questions_created_at_idx"),
        ),
    ]
