# Generated by Django 5.0.2 on 2026-04-03

from django.db import migrations


def seed_questions_permissions(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    actions = ["view", "add", "change", "delete", "all"]
    permissions = {}

    for action in actions:
        permission, _ = Permission.objects.get_or_create(
            module="questions",
            action=action,
            defaults={"description": f"Questions {action}"},
        )
        permissions[action] = permission

    role_permissions = {
        "admin": ["all"],
        "receptionist": ["view", "add", "change"],
        "viewer": ["view"],
    }

    for role_name, role_actions in role_permissions.items():
        for action in role_actions:
            RolePermission.objects.get_or_create(
                role_name=role_name,
                permission=permissions[action],
            )


def reverse_seed_questions_permissions(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    questions_permissions = Permission.objects.filter(module="questions")
    RolePermission.objects.filter(permission__in=questions_permissions).delete()
    questions_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("core", "0009_add_questions_module_choice"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_questions_permissions, reverse_seed_questions_permissions),
    ]
