# Generated by Django 6.0.2 on 2026-02-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_backfill_staff_and_trainer_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('clerk', 'Clerk'), ('manager', 'Manager'), ('cleaner', 'cleaner'), ('other', 'Other')], max_length=20),
        ),
    ]
