# Generated by Django 6.0.2 on 2026-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_position'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staff',
            name='staff_att_st_idx',
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('clerk', 'Clerk'), ('manager', 'Manager'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='attendance_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_attendance_date',
        ),
    ]
