# Generated by Django 5.0.2 on 2026-03-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("father_name", models.CharField(blank=True, max_length=150)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("instructor", "Instructor"), ("staff", "Staff")],
                        max_length=20,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("work_days", models.JSONField(blank=True, default=list)),
                ("join_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["role"], name="employees_role_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="employees_status_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["join_date"], name="employees_join_date_idx"),
        ),
    ]
