# Generated by Django 5.2.11 on 2026-03-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_seed_employees_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_role_4146a9_idx',
            old_name='employees_role_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_status_0192ac_idx',
            old_name='employees_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_join_da_8f8d98_idx',
            old_name='employees_join_date_idx',
        ),
    ]
