# Generated by Django 5.0.2 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_rename_employees_role_idx_employees_role_4146a9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="employees/profile_pictures/"),
        ),
    ]
