# Generated by Django 5.0.2 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_add_employee_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(choices=[("male", "Male"), ("female", "Female"), ("other", "Other")], max_length=10, default="male"),
            preserve_default=False,
        ),
    ]
