# Generated by Django 5.0.2 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_subjects_module_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard"),
                    ("settings", "Settings"),
                    ("users", "Users"),
                    ("employees", "Employees"),
                    ("students", "Students"),
                    ("subjects", "Subjects"),
                    ("questions", "Questions"),
                ],
                max_length=50,
            ),
        ),
    ]
